### ISSUE TITLE
1.9 version

### ISSUE THREAD

**Issue by Eluinhost** [Eluinhost/FancyFreeze#2]
Need NMS setting up for 1.9 version, will release as v1.1.0 for use with UHC 1.1.0

@D4mnx are you running with this one or shall I finish it?

**Comment by ghost** [comment]
There were some NMS changes with MobEffect in 1.9 so the 1.9 feature branch probably needs some changes.

I'm using an event-based freeze as of right now but I'm definitely migrating to this if a 1.9 version is available.

**Comment by Eluinhost** [comment]
Alright I'll get to this tonight/tomorrow and get the implementation done

**Comment by Eluinhost** [comment]
~~Going to require a 1.9-R0.1-SNAPSHOT and 1.9.2-R0.1-SNAPSHOT versions~~
